name    'reidmv-mcollective'
version '0.0.1'
source 'https://github.com/reidmv/puppet-module-mcollective'
author 'Reid Vandewiele'
license 'Apache License, Version 2.0'
description 'Module to configure mcollective'
